stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .venv/


build:
  stage: build
  only:
    - merge_requests
  script:
    - export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1
    - python -m venv .venv
    - .venv/bin/pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

pytest:
  stage: test
  only:
    - merge_requests
  script:
    - .venv/bin/pytest tests --cov=etl --cov-report=term --cov-branch

deploy:
  stage: deploy
  only:
    - branches@airflow-datapipline/etl-engine
  except:
    - master@airflow-datapipline/etl-engine
  script:
    - curl -v 10.1.20.226:9999

deploy_prod:
  stage: deploy
  only:
    - master@airflow-datapipline/etl-engine
  script:
    - curl -v 172.31.16.24:9999
  when: manual
