stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1
    - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

pytest:
  stage: test
  image: python:3.6
  script:
    - pytest tests --cov=etl --cov-report=term --cov-branch

deploy:
  stage: deploy
  script:
    - fab deploy
