pytest:
  image: python:3.6
  script:
    - export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1
    - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    - pytest tests --cov=etl --cov-report=term --cov-report=html --cov-branch
