version: '3'

services:
  gunicorn:
    image: etl-engine
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    stop_signal:
      SIGTERM
    environment:
      ETL_ENVIREMENT: "${ETL_ENVIREMENT:-docker_dev}"
      VIRTUAL_HOST: "${VIRTUAL_HOST:-localhost}"
  huey:
    image: etl-engine
    volumes:
      - .:/app
    environment:
      ETL_ENVIREMENT: "${ETL_ENVIREMENT:-docker_dev}"
    command: huey_consumer.py etl.tasks.main.huey -k thread -w 8
    depends_on:
      - redis
    stop_signal:
      SIGINT
  celery:
    image: etl-engine
    volumes:
      - .:/app
    environment:
      ETL_ENVIREMENT: "${ETL_ENVIREMENT:-docker_dev}"
    command: celery -A celery_worker.celery worker -l info
    depends_on:
      - redis
    stop_signal:
      SIGINT
  redis:
    image: redis:4
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "5000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - gunicorn
