version: '3'

services:
  gunicorn:
    image: etl-engine
    build: .
    depends_on:
      - redis
    stop_signal:
      SIGTERM
    environment:
      ETL_ENVIREMENT: "${ETL_ENVIREMENT:-docker_dev}"
      VIRTUAL_HOST: "${VIRTUAL_HOST:-localhost}"
    restart: always
  celery:
    image: etl-engine
    environment:
      ETL_ENVIREMENT: "${ETL_ENVIREMENT:-docker_dev}"
    command: celery -A manage.celery worker -l info -Q etl,rollback,ext_history
    depends_on:
      - redis
    stop_signal:
      SIGTERM
    restart: always
  redis:
    image: redis:4
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports: 
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "5000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - gunicorn
    restart: always
