version: "3.4"

x-etl-engine: &default-app
  image: $MAIN_IMAGE
  environment:
    ETL_ENVIREMENT: "${ETL_ENVIREMENT:-docker_dev}"
    VIRTUAL_HOST: "${VIRTUAL_HOST:-localhost}"
    REDSHIFT_URL: "${REDSHIFT_URL}"
    SQLALCHEMY_DATABASE_URI: "${SQLALCHEMY_DATABASE_URI}"
    CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
    CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
    AIRFLOW_DB_URL: "${AIRFLOW_DB_URL}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
  stop_signal: SIGTERM

services:
  gunicorn:
    <<: *default-app
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: global
    ports:
      - "${PORT:-50010}:5000"
  celery:
    <<: *default-app
    command: celery -A manage.celery worker -l info -Q etl,rollback,ext_history, inventory
    stop_signal: SIGTERM
    deploy:
      mode: global
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "${PORT:-5000}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    restart: always
